# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: sepolia
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USDC
    addressOrDenom: "0xb0E03bf85baca7874C44Dbe2C961515e7F4529fe"
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: fuel|fueltestnet|0xfe93aaebea83b024776d0f842aa4ecf812c5ad762790534a99285b95452b060a
  - chainName: fueltestnet
    standard: FuelHypSynthetic
    decimals: 6
    symbol: USDC
    name: USDC
    addressOrDenom: "0xfe93aaebea83b024776d0f842aa4ecf812c5ad762790534a99285b95452b060a"
    connections:
      - token: ethereum|sepolia|0xb0E03bf85baca7874C44Dbe2C961515e7F4529fe
