# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xb0E03bf85baca7874C44Dbe2C961515e7F4529fe"
    chainName: sepolia
    collateralAddressOrDenom: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"
    connections:
      - token: fuel|fueltestnet|0xfe93aaebea83b024776d0f842aa4ecf812c5ad762790534a99285b95452b060a
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: EvmHypCollateral
    symbol: USDC
  - addressOrDenom: "0xfe93aaebea83b024776d0f842aa4ecf812c5ad762790534a99285b95452b060a"
    chainName: fueltestnet
    connections:
      - token: ethereum|sepolia|0xb0E03bf85baca7874C44Dbe2C961515e7F4529fe
    decimals: 6
    logoURI: /deployments/warp_routes/USDC/logo.svg
    name: USDC
    standard: FuelHypSynthetic
    symbol: USDC
