# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xb94903d736789fd36c7f77f86e89a486bb4c11c8"
    chainName: sepolia
    connections:
      - token: fuel|fueltestnet|0x43c94eff3e3d8832d5e69cb441ba94c6cd2ad83fb496497aee6f5b78b5b02ba0
    decimals: 18
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: EvmHypNative
    symbol: ETH
  - addressOrDenom: "0x43c94eff3e3d8832d5e69cb441ba94c6cd2ad83fb496497aee6f5b78b5b02ba0"
    chainName: fueltestnet
    connections:
      - token: ethereum|sepolia|0xb94903d736789fd36c7f77f86e89a486bb4c11c8
    decimals: 9
    logoURI: /deployments/warp_routes/ETH/logo.svg
    name: Ether
    standard: FuelHypSynthetic
    symbol: ETH
