# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: sepolia
    standard: EvmHypCollateral
    decimals: 9
    symbol: FUEL
    name: FUEL
    addressOrDenom: "0xF26ae2119e415856d768826a9C0B6c82f5C8115b"
    collateralAddressOrDenom: "0xd7Fc4e8FB2c05567C313f4C9b9e07641a361a550"
    connections:
      - token: fuel|fueltestnet|0xf3b4243c1f32ae590eaaaa60af7867bc06fd27fa4637f89d9e675d21f466c4e6
  - chainName: fueltestnet
    standard: FuelHypSynthetic
    decimals: 9
    symbol: HypFuel
    name: Testnet HypFuel
    addressOrDenom: "0xf3b4243c1f32ae590eaaaa60af7867bc06fd27fa4637f89d9e675d21f466c4e6"
    connections:
      - token: ethereum|sepolia|0xF26ae2119e415856d768826a9C0B6c82f5C8115b
